name: Metrics

on:
  schedule: [{cron: "0 0 * * 0"}]  # Cada domingo
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_achievements: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
